name: Create and terminate EC2 instance
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Test/Prod'
        required: true
  push:
    branches: 
      - main
jobs:
  create-and-terminate-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-southeast-1
      - name: Create and terminate EC2 instance
        run: |
          chmod +x create-ec2-instance1.sh
          ./create-ec2-instance1.sh
